name: Windows Workflow
on: workflow_dispatch
  #schedule:
  # * is a special character in YAML so you have to quote this string
  # This example triggers the workflow every day at 5:30AM UTC
  #  - cron: '30 5 * * *'

jobs:
  k6_local_test:
    name: k6 local test run on windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0' # The Go version to download (if necessary) and use.
          
      # Install all the dependencies
      - name: Install dependencies and XK6
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get -u github.com/k6io/xk6/cmd/xk6
          xk6 build

      
      - name: download and extract k6 release binaries
        run: |
          curl -L https://github.com/loadimpact/k6/releases/download/v0.25.1/k6-v0.25.1-win64.zip -o k6.zip
          7z.exe e k6.zip
        shell: bash

      - name: k6 test
        run: ./k6.exe run testingK6.js
        shell: bash
