name: Windows Workflow
on: workflow_dispatch
  #schedule:
  # * is a special character in YAML so you have to quote this string
  # This example triggers the workflow every day at 5:30AM UTC
  #  - cron: '30 5 * * *'

jobs:
  k6_local_test:
    name: k6 local test run on windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
          
      - name: Check build
        run: |
            go version
            pwd && ls -l
            export CGO_ENABLED=0
            
            go install go.k6.io/xk6/cmd/xk6@master
            GOPRIVATE="go.k6.io/k6" xk6 build \
              --output ./k6ext \
              --with github.com/grafana/xk6-output-prometheus-remote="."
            ./k6ext version
      
      - name: download and extract k6 release binaries
        run: |
          curl -L https://github.com/loadimpact/k6/releases/download/v0.25.1/k6-v0.25.1-win64.zip -o k6.zip
          7z.exe e k6.zip
        shell: bash

      - name: k6 test
        run: ./k6.exe run testingK6.js
        shell: bash
