name: K6 on linux
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  

defaults:
  run:
    shell: bash

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Check build
        run: |
            go version
            pwd && ls -l
            export CGO_ENABLED=0
            
            go install go.k6.io/xk6/cmd/xk6@master
            GOPRIVATE="go.k6.io/k6" xk6 build \
              --output ./k6ext \
              --with github.com/grafana/xk6-output-prometheus-remote="."
            ./k6ext version
            

      - name: Run k6 local test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: testingK6.js
          flags: --vus 2 --duration 5s
            
      
